-- Actualiza la columna DIAS_DESDE_ULTIMA_REVISION en la tabla FACT_SALES a NULL donde contiene cadenas vacías.
UPDATE DATAEX.FACT_SALES
SET DIAS_DESDE_ULTIMA_REVISION = NULL
WHERE DIAS_DESDE_ULTIMA_REVISION = '';

-- Elimina los puntos decimales de la columna DIAS_DESDE_ULTIMA_REVISION y la convierte a un entero donde contiene valores decimales.
UPDATE DATAEX.FACT_SALES
SET DIAS_DESDE_ULTIMA_REVISION = CAST(REPLACE(DIAS_DESDE_ULTIMA_REVISION, '.', '') AS INT)
WHERE DIAS_DESDE_ULTIMA_REVISION LIKE '%.%';

-- Cambia la columna DIAS_DESDE_ULTIMA_REVISION en la tabla FACT_SALES a tipo entero y la establece como NOT NULL.
ALTER TABLE DATAEX.FACT_SALES
ALTER COLUMN DIAS_DESDE_ULTIMA_REVISION INT;
