-- Set Customer_ID column as NOT NULL
ALTER TABLE DATAEX.DIM_LUGAR
ALTER COLUMN TIENDA_ID int NOT NULL;

-- Set Customer_ID column as NOT NULL
ALTER TABLE DATAEX.DIM_PRODUCTO
ALTER COLUMN Id_Producto nvarchar(255) NOT NULL;

-- Set CODE column as NOT NULL
ALTER TABLE DATAEX.FACT_SALES
ALTER COLUMN CODE nvarchar(255) NOT NULL;

-- Set Sales_Date column as NOT NULL
ALTER TABLE DATAEX.FACT_SALES
ALTER COLUMN Sales_Date nvarchar(255) NOT NULL;

-- Set Customer_ID column as NOT NULL
ALTER TABLE DATAEX.FACT_SALES
ALTER COLUMN Customer_ID int NOT NULL;


ALTER TABLE DATAEX.FACT_SALES
ALTER COLUMN DIAS_DESDE_ULTIMA_REVISION INT;


ALTER TABLE DATAEX.FACT_SALES
ALTER COLUMN Id_Producto nvarchar(255) NOT NULL;

ALTER TABLE DATAEX.FACT_SALES
ALTER COLUMN PVP int NOT NULL;

ALTER TABLE DATAEX.FACT_SALES
ALTER COLUMN IMPUESTOS int NOT NULL;

ALTER TABLE DATAEX.FACT_SALES
ALTER COLUMN COSTE_VENTA_NO_IMPUESTOS int NOT NULL;

ALTER TABLE DATAEX.FACT_SALES
ALTER COLUMN Forma_Pago nvarchar(255) NOT NULL;

ALTER TABLE DATAEX.FACT_SALES
ALTER COLUMN Motivo_Venta nvarchar(255) NOT NULL;

ALTER TABLE DATAEX.FACT_SALES
ALTER COLUMN TIENDA_ID int NOT NULL;

ALTER TABLE DATAEX.FACT_SALES
ALTER COLUMN Tienda nvarchar(255) NOT NULL;

ALTER TABLE DATAEX.FACT_SALES
ALTER COLUMN Modelo nvarchar(255) NOT NULL;

ALTER TABLE DATAEX.FACT_SALES
ALTER COLUMN Costetransporte float NOT NULL;

ALTER TABLE DATAEX.FACT_SALES
ALTER COLUMN GastosMarketing float NOT NULL;

ALTER TABLE DATAEX.FACT_SALES
ALTER COLUMN Margendistribuidor float NOT NULL;

ALTER TABLE DATAEX.FACT_SALES
ALTER COLUMN Comisión_Marca float NOT NULL;

ALTER TABLE DATAEX.FACT_SALES
ALTER COLUMN Margen_eur_bruto float NOT NULL;

ALTER TABLE DATAEX.FACT_SALES
ALTER COLUMN Margen_eur float NOT NULL;

---Establecemos que no hay valores nulos en ninguna de las columnas de la tabla dim tiempo
ALTER TABLE DATAEX.DIM_TIEMPO
ALTER COLUMN Date nvarchar(255) NOT NULL;

ALTER TABLE DATAEX.DIM_TIEMPO
ALTER COLUMN Dia int NOT NULL;

ALTER TABLE DATAEX.DIM_TIEMPO
ALTER COLUMN Mes int NOT NULL;

ALTER TABLE DATAEX.DIM_TIEMPO
ALTER COLUMN Anno int NOT NULL;

ALTER TABLE DATAEX.DIM_TIEMPO
ALTER COLUMN Week int NOT NULL;

ALTER TABLE DATAEX.DIM_TIEMPO
ALTER COLUMN InicioMes nvarchar(255) NOT NULL;

ALTER TABLE DATAEX.DIM_TIEMPO
ALTER COLUMN Diadelasemana int NOT NULL;

ALTER TABLE DATAEX.DIM_TIEMPO
ALTER COLUMN Annomes int NOT NULL;

ALTER TABLE DATAEX.DIM_TIEMPO
ALTER COLUMN FinMes nvarchar(255) NOT NULL;

ALTER TABLE DATAEX.DIM_TIEMPO
ALTER COLUMN Findesemana nvarchar(255) NOT NULL;

ALTER TABLE DATAEX.DIM_TIEMPO
ALTER COLUMN Festivo nvarchar(255) NOT NULL;

ALTER TABLE DATAEX.DIM_TIEMPO
ALTER COLUMN Laboral nvarchar(255) NOT NULL;

ALTER TABLE DATAEX.DIM_TIEMPO
ALTER COLUMN Diadelesemana_desc nvarchar(255) NOT NULL;

ALTER TABLE DATAEX.DIM_TIEMPO
ALTER COLUMN Mes_desc nvarchar(255) NOT NULL;

ALTER TABLE DATAEX.DIM_CLIENTE
ALTER COLUMN Customer_ID int NOT NULL;

ALTER TABLE DATAEX.DIM_CLIENTE
ALTER COLUMN CODIGO_POSTAL_LIMPIO nvarchar(255) NOT NULL;

ALTER TABLE DATAEX.DIM_CLIENTE
ALTER COLUMN Edad int NOT NULL;

ALTER TABLE DATAEX.DIM_CLIENTE
ALTER COLUMN GENERO nvarchar(255) NOT NULL;

ALTER TABLE DATAEX.DIM_CLIENTE
ALTER COLUMN Fecha_nacimiento nvarchar(255) NOT NULL;

ALTER TABLE DATAEX.DIM_CLIENTE
ALTER COLUMN RENTA_MEDIA_ESTIMADA int NOT NULL;

ALTER TABLE DATAEX.DIM_CLIENTE
ALTER COLUMN STATUS_SOCIAL nvarchar(255) NOT NULL;

ALTER TABLE DATAEX.DIM_CLIENTE
ALTER COLUMN Poblacion nvarchar(255) NOT NULL;

ALTER TABLE DATAEX.DIM_CLIENTE
ALTER COLUMN Provincia nvarchar(255) NOT NULL;

ALTER TABLE DATAEX.DIM_CLIENTE
ALTER COLUMN A float NOT NULL;

ALTER TABLE DATAEX.DIM_CLIENTE
ALTER COLUMN B float NOT NULL;

ALTER TABLE DATAEX.DIM_CLIENTE
ALTER COLUMN C float NOT NULL;

ALTER TABLE DATAEX.DIM_CLIENTE
ALTER COLUMN D float NOT NULL;

ALTER TABLE DATAEX.DIM_CLIENTE
ALTER COLUMN E float NOT NULL;

ALTER TABLE DATAEX.DIM_CLIENTE
ALTER COLUMN F float NOT NULL;

ALTER TABLE DATAEX.DIM_CLIENTE
ALTER COLUMN G float NOT NULL;

ALTER TABLE DATAEX.DIM_CLIENTE
ALTER COLUMN H float NOT NULL;

ALTER TABLE DATAEX.DIM_CLIENTE
ALTER COLUMN I float NOT NULL;

ALTER TABLE DATAEX.DIM_CLIENTE
ALTER COLUMN J float NOT NULL;

ALTER TABLE DATAEX.DIM_CLIENTE
ALTER COLUMN K float NOT NULL;

ALTER TABLE DATAEX.DIM_CLIENTE
ALTER COLUMN U2 float NOT NULL;

ALTER TABLE DATAEX.DIM_CLIENTE
ALTER COLUMN Max_Mosaic_G nvarchar(255) NOT NULL;

ALTER TABLE DATAEX.DIM_CLIENTE
ALTER COLUMN Max_Mosaic2 float NOT NULL;

ALTER TABLE DATAEX.DIM_CLIENTE
ALTER COLUMN Renta_Media float NOT NULL;

ALTER TABLE DATAEX.DIM_CLIENTE
ALTER COLUMN F2 float NOT NULL;

ALTER TABLE DATAEX.DIM_CLIENTE
ALTER COLUMN Max_Mosaic nvarchar(255) NOT NULL;

ALTER TABLE DATAEX.DIM_CLIENTE
ALTER COLUMN Mosaic_number float NOT NULL;